name: lask
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  # salomon_bottom_bar: ^3.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_inset_box_shadow: ^1.0.8

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/appLogo.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  get: ^4.6.5
  dotted_line: ^3.1.0
  intl: ^0.18.1
  shared_preferences: ^2.1.2
  curved_nav_bar:
    git:
      url: git@github.com:mananKoyawala/package_curverd_nav_bar.git
      ref: master
  button_tab:
    git:
      url: git@github.com:mananKoyawala/package_button_tab.git
      ref: master
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  fluttertoast: ^8.2.2
  http: ^0.13.6
  shimmer: ^3.0.0
  jumping_dot: ^0.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: fonts
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.otf
