// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgWQUFIQPR2soxE4mdCAQdPFS-4HtoG4',
    appId: '1:389574323327:web:93faf7f69d0f7dede9a34a',
    messagingSenderId: '389574323327',
    projectId: 'lask-177aa',
    authDomain: 'lask-177aa.firebaseapp.com',
    storageBucket: 'lask-177aa.appspot.com',
    measurementId: 'G-RPLQ7S26X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpLk1zjC8IiONaFTR1OHdu2X1v7T02hwA',
    appId: '1:389574323327:android:c4ea73eeabc8456fe9a34a',
    messagingSenderId: '389574323327',
    projectId: 'lask-177aa',
    storageBucket: 'lask-177aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGyeAu4Bl3SvZJeiwYzX0f9c1llB2lKI',
    appId: '1:389574323327:ios:61529050e530afb8e9a34a',
    messagingSenderId: '389574323327',
    projectId: 'lask-177aa',
    storageBucket: 'lask-177aa.appspot.com',
    androidClientId: '389574323327-90bhmmvn5p1j0ub3rmgtmkj4912b42vv.apps.googleusercontent.com',
    iosClientId: '389574323327-33ggc1m067u3t06itou2hkaojnl3db52.apps.googleusercontent.com',
    iosBundleId: 'com.example.lask',
  );
}
